# _config.yml - Last updated: 2025-12-09T19:10

title: Blog
description: "A blog about Cybersecurity"

# Collections
collections:
  shares:
    output: false
    sort_by: date
  tweets:
    output: false
    sort_by: date

